# Generated by Django 5.2.17 on 2026-09-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='contact',
            field=models.CharField(default='Sin contacto', max_length=255),
        ),
    ]
