# Generated by Django 5.2.17 on 2026-10-04 18:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_limit_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('6.00'), max_digits=4),
        ),
    ]
