# Generated by Django 5.2.17 on 2026-10-03 18:16

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_user_daily_limit_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_limit_configured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='daily_limit_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal("6.00"), max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)]),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('daily_limit_hours__gte', 1), ('daily_limit_hours__lte', 16)), name='user_daily_limit_between_1_and_16'),
        ),
    ]
