# Generated by Django 5.2.17 on 2026-10-03 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_user_daily_limit_configured_and_more'),
    ]

    operations = []
